PlannerPausePlay/PlannerPausePlay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from members import views as members_views


urlpatterns = [
 path('admin/', admin.site.urls),
 path('', members_views.admin_landpage, name='admin_landpage'),  #  admin_home as  landing page
 path('members',include('django.contrib.auth.urls')),
 path('members/',include('members.urls')),
 path('vacayvue/', include('VacayVue.urls')),  

]
# Serving static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PlannerPausePlay/VacayVue/urls.py
from django.urls import path
from  VacayVue import views

#url config
urlpatterns = [
    path('main_home/', views.main_home, name='main_home'),
    path('login/', views.login_user, name="login"),
    path('logout_user/', views.logout_user, name="logout"),
   
   


    path('employee_home/',views.employee_home,name="employee_home"),
    path('my_requests/',views.my_requests,name="my_requests"),
    path('delete_pending_request/<int:request_id>/', views.delete_pending_request, name='delete_pending_request'),
    path('add_employee/', views.add_employee, name="add_employee"),
      
    path('list_employees/',views.list_employees,name="list_employees"),
    path('show-employee/<int:employee_id>/', views.employee_details, name='employee_details'),
    path('edit-employee/<int:employee_id>/', views.update_employee, name='update_employee'),
    path('delete-employee/<int:employee_id>/', views.delete_employee, name='delete_employee'),

    path('company_home/', views.company_home, name='company_home'),
    path('add_request/',views.add_request,name='add_request'),

    path('list_requests/',views.list_all_requests,name='list_all_requests'),
    path('delete_request/<int:request_id>/', views.delete_request, name='delete_request'),
   path('approve_leave_request/<int:request_id>/', views.handle_leave_request, {'action': 'approve'}, name='approve_leave_request'),
    path('request_details/<int:request_id>/', views.request_details, name='request_details'),

    path('update_default_days/<int:leave_type_id>/', views.update_default_days, name='update_default_days'),
    path('manage_leave_type/', views.manage_leave_type, name='manage_leave_type'),
    path('balance-data/', views.balance_data, name='balance_data'),
    path('get_target_month/', views.get_target_month, name='get_target_month'),
  
    #path('change-password/', views.change_password, name='change_password'),

    path('calendar/', views.calendar, name='calendar'),
    path('all_requests/', views.all_requests, name='all_requests'),
    path('add_custom_holiday/', views.add_custom_holiday, name='add_custom_holiday'),
    
    
   
   # path('error_template/', views.error_template,name="error_template")



    
 
]

PlannerPausePlay/members/urls.py
from django.urls import path
from  .import views

urlpatterns = [
    path('',views.admin_landpage,name="admin_landpage"),
    path('admin_home/',views.admin_home,name="admin_home"),
    path('logout_admin/', views.logout_admin, name="logout_admin"),
    path('register_company/',views.register_company,name="register_company"),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_register/', views.admin_register, name='admin_register'),
    path('switch_to_company_login/', views.switch_to_company_login, name='switch_to_company_login'),





    
]

PlannerPausePlay/VacayVue/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings


class CustomUser(AbstractUser):
    USER_TYPE_CHOICES = [
        ('employee', 'Employee'),
        ('company', 'Company'),
        ('admin', 'Admin'),
    ]

    permissions = models.CharField(max_length=255, null=True, blank=True)
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES)
    role = models.CharField(max_length=100, null=True)
    is_admin = models.BooleanField(default=False)
    is_company = models.BooleanField(default=False)  # New field to indicate if user is a company
    is_employee = models.BooleanField(default=False)  # New field to indicate if user is an employee

    company = models.ForeignKey('Company', on_delete=models.SET_NULL, null=True, blank=True, related_name='employees')

    def save(self, *args, **kwargs):
        if self.user_type == 'company':
            self.is_company = True
        elif self.user_type == 'employee':
            self.is_employee = True
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username

class Admins(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)

class Company(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='company_profile')
    name = models.CharField(max_length=255)
    hr_name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Employee(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='employee_profile', unique=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='employees_company')
    join_date = models.DateField(null=True, blank=True)
    first_name = models.CharField(max_length=30, null=True)
    last_name = models.CharField(max_length=150, null=True)

    def __str__(self):
        return self.user.email
#request ειναι 1:1 σχεση .Μια ετηση για καθε υπαλλοιλο
class Requests(models.Model):
    APPROVED = 'approved'
    REJECTED = 'rejected'
    PENDING = 'pending'  # Status when request is submitted

    STATUS_CHOICES = [
        (APPROVED, 'Approved'),
        (REJECTED, 'Rejected'),
        (PENDING, 'Pending'),
    ]

    request_id = models.AutoField(primary_key=True)
    EmployID = models.ForeignKey(Employee,related_name='requests', blank=True, null=True, on_delete=models.CASCADE)
    StartDate = models.DateTimeField(null=True, blank=True)
    EndDate = models.DateTimeField(null=True, blank=True)
    Type = models.CharField(max_length=50)
    Status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=PENDING)
    Comments = models.TextField(blank=True)

    def __str__(self):
        return self.Type


class Events(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    start = models.DateTimeField(null=True, blank=True)
    end = models.DateTimeField(null=True, blank=True)
    class Meta:
        db_table = "tblevents"






'''
class TeamMembers(models.Model):
    TeamMemberID = models.AutoField(primary_key=True)
    UserID = models.ForeignKey(Users, on_delete=models.CASCADE)
    TeamLeadID = models.ForeignKey(Users, on_delete=models.CASCADE, related_name='team_lead')
    CalendarViewPermission = models.BooleanField()


class AuditTrail(models.Model):
    ACTION_CHOICES = [
        ('approve', 'Approve'),
        ('reject', 'Reject'),
    ]
    AuditTrailID = models.AutoField(primary_key=True)
    RequestID = models.ForeignKey(Requests, on_delete=models.CASCADE)
    ActionTimestamp = models.DateTimeField(auto_now_add=True)
    ApproverID = models.ForeignKey(Users, on_delete=models.CASCADE)
    Action = models.CharField(max_length=50)
    Comments = models.TextField()

class Calendar(models.Model):
    STATUS_CHOICES = [
        ('holiday', 'Holiday'),
        ('day_off', 'Day Off'),
    ]
    Date = models.DateField(primary_key=True)
    Status = models.CharField(max_length=50)

class Holidays(models.Model):
    HolidayID = models.AutoField(primary_key=True)
    HolidayName = models.CharField(max_length=255)
    Date = models.DateField()

class PublicHolidays(models.Model):
    HolidayID = models.AutoField(primary_key=True)
    Country = models.CharField(max_length=255)
    HolidayName = models.CharField(max_length=255)
    Date = models.DateField()

class CustomHolidays(models.Model):
    CustomHolidayID = models.AutoField(primary_key=True)
    UserID = models.ForeignKey(Users, on_delete=models.CASCADE)
    HolidayName = models.CharField(max_length=255)
    Date = models.DateField()

class Permissions(models.Model):
    PermissionID = models.AutoField(primary_key=True)
    Role = models.CharField(max_length=50)
    Feature = models.CharField(max_length=255)
    Allowed = models.BooleanField()

class TimeOffBalances(models.Model):
    BalanceID = models.AutoField(primary_key=True)
    UserID = models.ForeignKey(Users, on_delete=models.CASCADE)
    VacationBalance = models.IntegerField()
    SickLeaveBalance = models.IntegerField()
    #OtherLeaveBalance = models.IntegerField()
    Year = models.IntegerField()

class ApprovalWorkflow(models.Model):
    WorkflowID = models.AutoField(primary_key=True)
    Role = models.CharField(max_length=50)
    ApproverID = models.ForeignKey(Users, on_delete=models.CASCADE)
    MinimumApprovalLevel = models.IntegerField()







#class Notification(models.Model):
#   NotificationID = models.AutoField(primary_key=True)
#    UserID = models.ForeignKey(Users, on_delete=models.CASCADE)
#    Message = models.TextField()
#    Timestamp = models.DateTimeField(auto_now_add=True)
#    Status = models.CharField(max_length=50)


'''

PlannerPausePlay/VacayVue/forms.py
from django import forms
from django.forms import ModelForm
from .models import Request,CustomUser,Employee,LeaveType
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(widget=forms.PasswordInput)
    user_type = forms.ChoiceField(choices=(('υπάλληλο', 'υπάλληλο'), ('εταιρία', 'Εταιρία')), required=True)


class RegisterEmployeeForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control','placeholder': 'Email'}))
    join_date = forms.DateField(
    widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'Ημερομηνία Πρόσληψης', 'id': 'id_join_date','autocomplete': 'off'}),
    input_formats=['%d/%m/%Y']  # Adjusted format
)
    
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'data-toggle': 'tooltip', 'placeholder': 'Κωδικός','title': 'Your password must contain at least 8 characters and cannot be too similar to your other personal information.'})
    )
    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'data-toggle': 'tooltip','placeholder': 'Επιβεβαίωση Κωδικού','title': 'Please enter the same password for verification.'})
    )
    first_name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Όνομα'}))
    last_name = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Επίθετο'}))
    
    class Meta:
        model = CustomUser
        fields = ['email', 'join_date', 'password1', 'password2', 'first_name', 'last_name']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email
        user.user_type = 'υπάλληλο'
        if commit:
            user.save()
            employee=Employee.objects.create(
            user=user,#1 user is employee user
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            join_date=self.cleaned_data['join_date'],
            )
        return employee

class EditEmployeeForm(forms.ModelForm):
    join_date = forms.DateField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'Ημερομηνία Πρόσληψης', 'id': 'id_join_date','autocomplete': 'off'}),
        input_formats=['%Y-%m-%d']  # Format expected by Django
    )

    class Meta:
        model = Employee
        fields = ['first_name', 'last_name', 'join_date']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
        }


#-------------------------------------------------------------------------------------------------------------------------------------------

CHOICES = (
        ('Κανονική Άδεια', 'Κανονική Άδεια'),
        ('Αδεια Εξετάσεων Εργαζόμενων Σπουδαστών', 'Αδεια Εξετάσεων Εργαζόμενων Σπουδαστών'),
        ('Αδεια Εξετάσεων Μεταπτυχιακών Φοιτητών', 'Αδεια Εξετάσεων Μεταπτυχιακών Φοιτητών'),
        ('Αιμοδοτική Άδεια', 'Αιμοδοτική Άδεια'),
        ('Άδεια Άνευ Αποδοχών', 'Άδεια Άνευ Αποδοχών'),
        ('Άδεια Μητρότητας', 'Άδεια Μητρότητας'),
        ('Άδεια Πατρότητας', 'Άδεια Πατρότητας'),
    )
MONTH_CHOICES = (
        (1, 'Ιανουάριος'),(2, 'Φεβρουάριος'),(3, 'Μάρτιος'),(4, 'Απρίλιος'),
        (5, 'Μάιος'),(6, 'Ιούνιος'),(7, 'Ιούλιος'),(8, 'Αύγουστος'),
        (9, 'Σεπτέμβριος'),(10, 'Οκτώβριος'),(11, 'Νοέμβριος'),(12, 'Δεκέμβριος'),
    )
class LeaveTypeForm(forms.ModelForm):
    update_mode = forms.BooleanField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = LeaveType
        fields = ['name', 'default_days', 'reset_month', 'update_mode']
        widgets = {
             'default_days': forms.TextInput(attrs={'class': 'form-control', 'pattern': r'\d*', 'placeholder': 'xxxx'}),
            'name': forms.Select(choices=CHOICES),
            'reset_month': forms.Select(choices=MONTH_CHOICES)
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'update_mode' in self.initial and self.initial['update_mode']:
            self.fields['reset_month'].disabled = False
        else:
            self.fields['reset_month'].disabled = True

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        reset_month = cleaned_data.get('reset_month')
        user = self.instance.user if self.instance and hasattr(self.instance, 'user') else None

        if self.instance and self.instance.pk:  # If updating an existing LeaveType
            return cleaned_data  # Skip validation for updates

        if name and reset_month and user:
            if LeaveType.objects.filter(user=user, name=name).exists():
                raise forms.ValidationError("A LeaveType with this name already exists for this user.")
            existing_leave_types = LeaveType.objects.filter(user=user)
            if existing_leave_types.exists() and reset_month != existing_leave_types.first().reset_month:
                raise forms.ValidationError({'reset_month': 'The reset month must be consistent for leave types with the same user.'})
        return cleaned_data

class RequestForm(ModelForm):
    leave_type = forms.ModelChoiceField(queryset=LeaveType.objects.none())  # Empty initial queryset

    start =forms.DateField(
       widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'ΗΗ/ΜΜ/ΧΧΧΧ', 'id': 'id_start','autocomplete': 'off'}),
       input_formats=['%d/%m/%Y']  # Adjusted format
    )

    end = forms.DateField(
       widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'ΗΗ/ΜΜ/ΧΧΧΧ', 'id': 'id_end','autocomplete': 'off'}),
       input_formats=['%d/%m/%Y']  # Adjusted format
    )


    class Meta:
        model = Request
        fields = ["leave_type", "start", "end", "description", 'document']
        widgets = {
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Περιγραφή Αιτήσεως",
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['leave_type'].queryset = LeaveType.objects.all()
        default_leave_type = LeaveType.objects.filter(name='Κανονική Άδεια').first()
        if default_leave_type:
            self.initial['leave_type'] = default_leave_type
#---------------------------------------------------------------------------------------#
class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(label='Current Password', widget=forms.PasswordInput)
    new_password = forms.CharField(label='New Password', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput)

class CustomHolidayForm(forms.Form):
    name = forms.CharField(max_length=100)
    date = forms.DateField(
    widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text', 'placeholder': 'Ημερομηνία ', 'id': 'id_date','autocomplete': 'off'}),
    input_formats=['%d/%m/%Y']  )

PlannerPausePlay/VacayVue/templates/vacayvue/add-request.html
{% extends 'vacayvue/base.html' %}

{% block content %}
<h4 class="text-center">Προσθήκη Αιτήματος στη Βάση</h4>
<br>
<div class="row justify-content-center">
  <div class="col-md-6">
    {% if submitted %}
    <div class="alert alert-success" role="alert">
      Η Αίτηση σας καταχωρήθηκε επιτυχώς!!!
    </div>
    {% else %}
    <form action="" method="POST" class="custom-form-container">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_Type" class="custom-form-label">Τύπος Άδειας</label>
        {{ form.Type }}
      </div>
      <div class="row">
        <div class="col">
          <div class="form-group">
            <label for="id_StartDate" class="custom-form-label">Ημερομηνία Έναρξης</label>
            <div class="input-group">
              {{ form.StartDate }}
              <button class="btn btn-outline-secondary" type="button" id="start-custom-calendar-icon">
                <i class="bi bi-calendar"></i>
              </button>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="form-group">
            <label for="id_EndDate" class="custom-form-label">Ημερομηνία Λήξης</label>
            <div class="input-group">
              {{ form.EndDate }}
              <button class="btn btn-outline-secondary" type="button" id="end-custom-calendar-icon">
                <i class="bi bi-calendar"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <label for="id_Comments" class="custom-form-label">Περιγραφή</label>
        {{ form.Comments }}
      </div>
      <br>
      <input type="hidden" name="submitted" value="True">
      <button type="submit" class="btn btn-secondary">Υποβολή</button>
    </form>
    {% endif %}
  </div>
</div>
{% endblock %}

PlannerPausePlay/VacayVue/templates/vacayvue/add_request.html
{% extends 'vacayvue/base.html' %}
{% load static %}



{% block content %}
<div class="row">
    <div class="col-md-5 border-image-container">
        <h3 class="title">Προσθήκη Αίτησης</h3>			
        <img src="{% static 'images/stripy5.png' %}" alt="Image" class="img-fluid">
    </div>
    <div class="col-md-7 main-content-section">
        <form action="{% url 'add_request' %}" method="POST" class="form-container" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_leave_type">Τύπος:</label>
                {{ form.leave_type }}
                {% if form.errors.leave_type %}
                    <div class="message error">{{ form.errors.leave_type }}</div>
                {% endif %}
            </div>
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_start">Έναρξη:</label>
                        {{ form.start }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="id_end">Λήξη:</label>
                        {{ form.end }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="id_description" class="form-label">Περιγραφή</label>
                <div class="input-group">
                    {{ form.description }}
                </div>
                <input type="file" name="documents" multiple class="custom-file-input">
            </div>
            <button type="submit" class="button">Υποβολή</button>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'js/datepicker-el.js' %}"></script>
<script src="{% static 'js/datepicker.js' %}"></script>
{% endblock %}

PlannerPausePlay/VacayVue/templates/vacayvue/home.html
{% extends 'vacayvue/base.html' %}

{% block content %}
<main>
    <section class="hero">
        <h2>Welcome to the Employee Day Off Manager!</h2>
        <p>This app helps you manage your employees' day off requests efficiently.</p>
    </section>

    <section class="features">
        <h2>Key Features</h2>
        <ul>
            <li>Submit and manage day off requests.</li>
            <li>View employee schedules and availability.</li>
            <li>Intuitive calendar interface for scheduling.</li>
            <li>Real-time notifications for request status updates.</li>
        </ul>
    </section>

    <section class="get-started">
        <h2>Get Started</h2>
        <p>Start managing your employees' day off requests today!</p>
       <!-- <a href="{% url 'register_company' %}" class="button">Sign Up</a>-->
        <a href="{% url 'login' %}" class="button">Login</a>
    </section>
    
</main>
{% endblock %}

PlannerPausePlay/VacayVue/templates/vacayvue/manage_leave_type.html
{% extends 'vacayvue/base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-md-12 full-width-container">
        <h3 class="title">Διαχείρηση Αδειών</h3>
        <div class="subtext-container">
            <p>Προσαρμόστε το σύστημα διαχείρισης αδειών χωρίς κόπο ώστε να ταιριάζει απόλυτα στις ανάγκες σας. 
                Ορίστε τους τύπους άδειας, εκχωρήστε προεπιλεγμένες ημέρες και επιλέξτε τον μήνα επαναφοράς με ευκολία:
            </p>
        </div>
        <div class="row">
            <div class="col-md-6 circle-image-container">
                <img src="{% static 'images/stripy2.png' %}" alt="Image" class="img-fluid ">
            </div>
            <div class="col-md-6 main-content-section">
                <form action="{% url 'manage_leave_type' %}" method="POST" class="form-container">
                    {% csrf_token %}
                    {{ form.hidden_field }}
                    <table class="leave-table">
                        <tr>
                            <td><label for="id_reset_month">Μήνας Επαναφοράς:</label></td>
                            <td>{{ form.reset_month }}</td>
                        </tr>
                        <tr>
                            <td><label for="id_name">Τύπος Αδείας:</label></td>
                            <td>{{ form.name }}</td>
                        </tr>
                        <tr id="unique-id-here">
                            <td><label for="id_default_days">Μέρες στον χρονο:</label></td>
                            <td>{{ form.default_days }}</td>
                        </tr>
                    </table>
                    <button id="add-leave-btn" type="submit" class="button">
                        <span class="plus-icon">&#43;</span>Προσθήκη
                    </button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-12 full-width-container">
        <div class="row">
            <div class="col-md-6 main-content-section">
                <table class="leave-table">
                    <thead class="leave-table-header">
                        <tr>
                            <th>Τύπος Άδειας:</th>
                            <th>Μέρες ανα Χρόνο:</th>
                        </tr>
                    </thead>
                    <tbody class="leave-table-body">
                        {% for leave_type in leave_types %}
                        <tr>
                            <td>{{ leave_type.name }}</td>
                            <td>{{ leave_type.default_days }}[<a href="{% url 'update_default_days' leave_type_id=leave_type.id %}">ενημέρωση</a>]</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="2">No leave types found</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-6 circle-image-container">
                <img src="{% static 'images/stripy1.png' %}" alt="Image" class="img-fluid ">
            </div>
        </div>
    </div>
</div>
{% endblock %}

PlannerPausePlay/VacayVue/templates/vacayvue/register_employee.html
{% extends 'vacayvue/base.html' %}

{% block content %}

<div class="shadow p-4 mb-5 bg-body rounded">
  <h4 class="text-center">Φόρμα Προσθήκης Εργαζομένων</h4>
  <br>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <form action="{% url 'register_employee' %}" method="POST" class="custom-form-container">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_Email" class="custom-form-label">Email</label>
          {{ form.email }}
        </div>
        <div class="form-group">
          <label for="id_first_name" class="custom-form-label">Όνομα</label>
          {{ form.first_name }}
        </div>
        <div class="form-group">
          <label for="id_last_name" class="custom-form-label">Επίθετο</label>
          {{ form.last_name }}
        </div>
        <div class="form-group">
          <label for="id_datejoined" class="custom-form-label">Ημερομηνία Έναρξης</label>
          <div class="input-group">
            {{ form.date_joined }}
            <button class="btn btn-outline-secondary" type="button" id="start-calendar-icon">
              <i class="bi bi-calendar"></i>
            </button>
          </div>
        </div>
        <div class="form-group">
          <label for="id_password1" class="custom-form-label">Κωδικός</label>
          {{ form.password1 }}
        </div>
        <div class="form-group">
          <label for="id_password2" class="custom-form-label">Επιβεβαίωση Κωδικού</label>
          {{ form.password2 }}
        </div>
        {% if request.method == 'POST' %}
        {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <p>Υπάρχει κάποιο σφάλμα με τη φόρμα σας</p>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}

        {% endif %}
        <input type="submit" value="Εγγραφή" class="button">
      </form>
    </div>
  </div>

</div>

{% endblock %}

PlannerPausePlay/VacayVue/templates/vacayvue/update_employee.html
{% extends 'vacayvue/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
      <div class="col-md-6 border-image-container">
        <h3 class="title">Ενημέρωση Στοιχείων</h3>
        <img src="{% static 'images/stripy7.png' %}" alt="Image" class="img-fluid ">
    </div>
        <div class="col-md-6">
            <div class="card custom-card">
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_first_name">Όνομα:</label>
                            {{ form.first_name }}
                        </div>
                        <div class="form-group">
                            <label for="id_last_name">Επίθετο:</label>
                            {{ form.last_name }}
                        </div>
                        <div class="form-group">
                            <label for="id_datejoined">Έναρξη</label>
                            {{ form.join_date }}
                        </div>
                        <input type="submit" value="Αποθήκευση" class="button">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script%}
<script src="{% static 'js/datepicker-el.js' %}"></script>
<script src="{% static 'js/datepicker.js' %}"></script>
{% endblock  %}