PlannerPausePlay/PlannerPausePlay/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from members import views as members_views


urlpatterns = [
 path('admin/', admin.site.urls),
 path('', members_views.admin_landpage, name='admin_landpage'),  #  admin_home as  landing page
 path('members',include('django.contrib.auth.urls')),
 path('members/',include('members.urls')),
 path('vacayvue/', include('VacayVue.urls')),  

]
# Serving static files during development
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

PlannerPausePlay/members/urls.py
from django.urls import path
from  .import views

urlpatterns = [
    path('',views.admin_landpage,name="admin_landpage"),
    path('admin_home/',views.admin_home,name="admin_home"),
    path('logout_admin/', views.logout_admin, name="logout_admin"),
    path('register_company/',views.register_company,name="register_company"),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_register/', views.admin_register, name='admin_register'),
    path('switch_to_company_login/', views.switch_to_company_login, name='switch_to_company_login'),





    
]

PlannerPausePlay/members/models.py
from django.db import models

# Create your models here.

PlannerPausePlay/members/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from VacayVue.models import CustomUser, Company
from django.contrib.auth.forms import UserCreationForm


class AdminLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(widget=forms.PasswordInput)

class AdminRegistrationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True,'class': 'form-control'}))

    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'data-toggle': 'tooltip', 'title': 'Your password must contain at least 8 characters and cannot be too similar to your other personal information.'})
    )
    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'data-toggle': 'tooltip', 'title': 'Please enter the same password for verification.'})
    )
    class Meta:
        model = CustomUser
        fields = ['email','password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email  # Set username as email
        user.is_admin = True  # Set is_admin flag to True
        if commit:
            user.save()
        return user

class RegisterCompanyForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True,'class': 'form-control'}))
    name = forms.CharField(max_length=255, label='Company Name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    hr_name = forms.CharField(max_length=255, label='HR Name', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'data-toggle': 'tooltip', 'title': 'Your password must contain at least 8 characters and cannot be too similar to your other personal information.'})
    )
    password2 = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'data-toggle': 'tooltip', 'title': 'Please enter the same password for verification.'})
    )

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'password1', 'password2', 'name', 'hr_name')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.username = user.email  # Set username as email
        user.user_type = 'company'

        if commit:
            user.save()
            # Create associated Companies instance
            Company.objects.create(
                user=user,
                name=self.cleaned_data['name'],
                hr_name=self.cleaned_data['hr_name']
            )

        return user

PlannerPausePlay/members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import  AdminLoginForm,AdminRegistrationForm,RegisterCompanyForm
#from django.contrib.auth.models import User
from VacayVue.models import Company
from django.http import HttpResponse



def admin_landpage(request):
    return render(request, 'authenticate/admin_landpage.html')


def admin_login(request):
    if request.method == 'POST':
        form = AdminLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            # Authenticate admin user
            user = authenticate(request, email=email, password=password)
            print(f"Email received in login view: {email}")  # Debugging statement

            if user is not None:
                print(f'User authenticated: {user}')
                print(f'User type: {user.user_type}')
                login(request, user)
                if user.user_type == 'admin':
                    return redirect('admin_home')  # Redirect to admin dashboard
            else:
                print('Authentication failed')  # Debugging statement
                # Incorrect credentials
                messages.error(request, 'Incorrect email or password.')
                return redirect('admin_login')
    else:
        form = AdminLoginForm()
    return render(request, 'authenticate/admin_login.html', {'form': form})


def admin_register(request):
    if request.method == 'POST':
        form = AdminRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.user_type = 'admin' 
            user.save()
            return redirect('admin_login')  # Redirect to admin login page
    else:
        form = AdminRegistrationForm()
    return render(request, 'authenticate/admin_register.html', {'form': form})

def admin_home(request):
    if request.user.is_authenticated and request.user.is_admin:
        if request.user.user_type == 'admin':
            related_companies = Company.objects.all()
            return render(request, 'authenticate/admin_home.html', {'related_companies': related_companies})
        else:
            return HttpResponse("You do not have permission to access this page.")
    else:
        return HttpResponse("Please log in to access this page.")


def logout_admin(request):
    logout(request)
    messages.success(request, 'Είσαι Αποσυνδεμένος')
    return redirect('admin_landpage')

def switch_to_company_login(request):
    if request.user.is_authenticated:
        logout(request)  # Log out the user
        return redirect('main_home')   # Redirect to main_home 
    else:
        return redirect('admin_home')  # Redirect to admin login page

def register_company(request):
    if request.method == 'POST':
        print(request.POST)
        form = RegisterCompanyForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.user_type ='company' 
            user.name = form.cleaned_data['name']  # Assign companyname from form
            user.hr_name = form.cleaned_data['hr_name']  # Assign hrname from form
            user.save()
            messages.success(request, f'Η Εταιρία {user.name} καταχωρηθηκε! ')
            return redirect('admin_home')  # Redirect to admin home page
        else:
            print(form.errors)
    else:
        form = RegisterCompanyForm()
    return render(request, 'authenticate/register_company.html', {'form': form})

PlannerPausePlay/members/templates/authenticate/admin_home.html
{% extends 'authenticate/base.html' %}

{% block content %}
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <!-- Register Company Form -->
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Καταχώρηση Εταιρίας</h5>
                        <a href="{% url 'register_company' %}" class="button">Προσθήκη</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <!-- View Registered Companies -->
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Καταχωρημένες Εταιρίες</h5>
                        <!-- Display list of registered companies here -->
                        <div class="table-responsive">
                            <table id="company-table" class="table">
                                <thead>
                                    <tr>
                                        <th>Όνομα Εταιρίας</th>
                                        <th>HR Όνομα</th>
                                        <th>Email Εταιρίας</th>
                                        <!-- Add more columns if needed -->
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for company in related_companies %}
                                    <tr>
                                        <td>{{ company.name }}</td>
                                        <td>{{ company.hr_name }}</td>
                                        <td>{{ company.user.email }}</td>
                                        <!-- Add more columns if needed -->
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

PlannerPausePlay/members/templates/authenticate/admin_landpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Landing Page</title>
        <!-- Custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/admin_landpage.css' %}">
 
</head>
<body>
    <div class="container">
        <h1>Welcome Admin!</h1>
        <a href="{% url 'admin_login' %}" class="btn btn-login">Login</a>
        <a href="{% url 'admin_register' %}" class="btn">Register</a>
    </div>
</body>
</html>

PlannerPausePlay/members/templates/authenticate/admin_login.html
{% extends 'authenticate/base.html' %}

{% block content %}

 {% if messages %}
 <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {% for message in messages %}
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {% endfor %}
</div>
 {% endif %}
 <div class="shadow p-3 mb-5 bg-body rounded">
    <h1 class="text-center"> Login Admin</h1>
    <br>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form action="" method="POST" class="form-container">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="id_email" class="form-label">Email</label>
                        {{ form.email }}
                    </div>
                    <div class="form-group">
                        <label for="id_password" class="form-label">Password</label>
                        {{ form.password }}
                    </div>
                    <button type="submit" class="button">Login</button>
                </form>
                
</div>
</div>
</div>

{% endblock %}

PlannerPausePlay/members/templates/authenticate/admin_navbar.html
<nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'admin_home' %}">Company Management</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                {% if not request.path == '/members/admin_home/' %}
                <!-- Show the back link only if the user is not on the home page -->
                <li class="nav-item">
                    <a class="nav-link" href="javascript:history.back()">
                        <i class="bi bi-arrow-left"></i> Back
                    </a>
                </li>
                {% endif %}
                <!-- Include other navigation links here -->
                {% if request.user.is_authenticated and  request.user.user_type == 'admin' %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout_admin' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'switch_to_company_login' %}">Εφαρμογή</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin_login' %}">Login</a>
                </li>
            {% endif %}
            
            </ul>
        </div>
    </div>
</nav>

PlannerPausePlay/members/templates/authenticate/admin_register.html
{% extends 'authenticate/base.html' %}

{% block content %}

{% if form.errors %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <p>Υπαρχει καποιο λαθος με τη φορμα σας</p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<div class="shadow p-4 mb-5 bg-body rounded">
  <h1 class="text-center">VacayVue Register</h1>

    <!-- Your form -->
    <form action="{% url 'admin_register' %}" method="POST">
      {% csrf_token %}
      {{ form }}
      <br>
      <input type="submit" value="Εγγραφη" class="btn btn-success">
  </form>
</div>

{% endblock %}

PlannerPausePlay/members/templates/authenticate/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bootstrap demo</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin_base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin_navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin_login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin_home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/register_company.css' %}">


    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/2.0.3/css/dataTables.bootstrap5.min.css">

    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
    <!-- FullCalendar -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>  
    <!-- Datepicker -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>

    <!-- DataTables JavaScript -->
    <script type="text/javascript" src="https://cdn.datatables.net/2.0.3/js/dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/2.0.3/js/dataTables.bootstrap5.min.js"></script>
    <!-- Custom JavaScript -->
    <script src="{% static 'js/datatable.js' %}"></script>   

</head>
<body>
    <div class="container">
        {% include 'authenticate/admin_navbar.html' %}

        {% block content %}
        <!-- Content block to be overridden by child templates -->
        {% endblock %}
    </div>
      
    <footer>
        Copyright (c) {{current_year}}
    </footer>
    


</body>
</html>

PlannerPausePlay/members/templates/authenticate/employee_home.html
{% extends 'vacayvue/base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <h1 class="text-center">Something for title</h1>

            {% include 'vacayvue/employee_navbar.html' %}

        </div>
        <div class="col-md-4">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <!-- Add your other div here -->
        </div>
    </div>
</div>
{% endblock %}

PlannerPausePlay/members/templates/authenticate/navbar.html
<nav class="navbar navbar-expand-lg ">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'admin_home' %}">Company Management</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                {% if not request.path == '/members/admin_home/' %}
                <!-- Show the back link only if the user is not on the home page -->
                <li class="nav-item">
                    <a class="nav-link" href="javascript:history.back()">
                        <i class="bi bi-arrow-left"></i> Back
                    </a>
                </li>
                {% endif %}
                <!-- Include other navigation links here -->
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout_admin' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'switch_to_company_login' %}">Εφαρμογή</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin_login' %}">Login</a>
                </li>
            {% endif %}
            
            </ul>
        </div>
    </div>
</nav>

PlannerPausePlay/members/templates/authenticate/register_company.html
{% extends 'authenticate/base.html' %}

{% block content %}

<div class="shadow p-4 mb-5 bg-body rounded">
  <h4 class="text-center">Φόρμα Προσθήκης Εταιριών</h4>
<br>
<div class="row justify-content-center">
  <div class="col-md-6">
    <form action="{% url 'register_company' %}" method="POST" class="custom-form-container">
      {% csrf_token %}
	  <div class="form-group">
        <label for="id_Email" class="custom-form-label">Email</label>
      {{ form.email }}
      </div>
      <div class="row">
        <div class="col">
          <div class="form-group">
            <label for="id_name" class="custom-form-label">Όνομα Εταιρίας</label>
				{{ form.name }}
		</div>
        </div>
        <div class="col">
          <div class="form-group">
            <label for="id_hr_name" class="custom-form-label">HR Όνομα</label>
				{{ form.hr_name }}
		</div>
        </div>
      </div>
      <div class="form-group">
        <label for="id_password1" class="custom-form-label">Κωδικός</label>
			{{ form.password1 }}
      </div>
	  <div class="form-group">
	  <label for="id_password2" class="custom-form-label">Επιβεβαίωση Κωδικού</label>
		{{ form.password2 }}
      </div>
      {% if request.method == 'POST' %}
      {% if form.errors %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <p>Υπαρχει καποιο λαθος με τη φορμα σας</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %}
    
    {% endif %}
      <input type="submit" value="Εγγραφη" class="button">
  </form>
  </div>
</div>

</div>

{% endblock %}

PlannerPausePlay/members/templates/authenticate/register_user.html
{% extends 'vacayvue/base.html' %}

{% block content %}

{% if form.errors %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <p>Υπαρχει καποιο λαθος με τη φορμα σας</p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

<div class="shadow p-4 mb-5 bg-body rounded">
  <h1 class="text-center">VacayVue Register</h1>

    <!-- Your form -->
    <form action="{% url 'register_user' %}" method="POST">
      {% csrf_token %}
      {{ form }}
      <br>
      <input type="submit" value="Εγγραφη" class="btn btn-success">
  </form>
</div>

{% endblock %}